[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fake-program = "3587AJrnBE5N6AgicmvC5ZrMt3a511jN2Ai4Nu78RXs9"
m6_1 = "2kiLeviDdmqdVkxhJ6uKuZo7SAASoxrCATHmjr5mNMzr"
rpg = "EwxLgTCGvabH6v1ELhRktRsSYbBUzMEmax9DoUzshJco"
soldev = "HzDUBzTLp7Zwb8WftkJvbhk67yjBS8uryvpBt1xTVdpe"
solsign = "s1g2tZuBvLAdvrvgp7utJ93LKjcjhfbEk5EHHWnF3yQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
